# 此文件为应用开发平台构建时读取的配置文件

# 前端配置
fe_enable=true
fe_path=
# 前端发布物目录，默认为 build/
#fe_build_artifacts=build/
# 前端镜像仓库，默认为：registry-vpc.cn-zhangjiakou.aliyuncs.com/yunli_mid_platform/resource:$project-fe-$version
#fe_docker_image=registry-vpc.cn-zhangjiakou.aliyuncs.com/yunli_mid_platform/resource:$project-fe-$version

# 后端配置
be_enable=true
be_path=be/
# 默认为 [项目名]-app/target/*.jar
#be_build_artifacts=yunli-service-framework-app/target/*.jar
# 后端镜像仓库， 默认为：registry-vpc.cn-zhangjiakou.aliyuncs.com/yunli_mid_platform/resource:$project-be-$version
#be_docker_image=registry-vpc.cn-zhangjiakou.aliyuncs.com/yunli_mid_platform/resource:$project-be-$version

# Chart配置
chart_enable=true
chart_path=chart/



