import { antdCompList, layerPageCompList, OneMapCompList, mapInteractionCompList } from './AntdComp';
// 组 1
const groupList = [
  {
    author: 'wangman',
    componentCode: '@yl/datai-com-group-basic',
    componentName: '组',
    englishName: 'GroupBasic',
    id: '1344247724305752065',
    imgUrl: 'assets/datai/icons/componentIcon/组合.png',
    status: 1,
    version: '0.0.1',
  },
];
// 基础文本 20
const basicTextList = [
  {
    author: 'wangman',
    componentCode: '@yl/datai-com-drop-down',
    componentName: '文本下拉', // v7.0 index 0
    englishName: 'DropDown',
    id: '1344239272921604098',
    imgUrl: 'assets/datai/icons/componentIcon/text/文本下拉.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'wangman',
    componentCode: '@yl/datai-com-text-basic',
    componentName: '文本', // v7.0 index 1
    englishName: 'TextBasic',
    id: '1344249366396739585',
    imgUrl: 'assets/datai/icons/componentIcon/text/文本.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'wangman',
    componentCode: '@yl/datai-com-flop-basic',
    componentName: '翻牌器', // v7.0 index 2
    englishName: 'FlopBasic',
    id: '1344242132551933954',
    imgUrl: 'assets/datai/icons/componentIcon/text/翻牌器.png',
    status: 1,
    version: '0.0.1',
    supportMobile: true,
  },
  {
    author: 'wangman',
    componentCode: '@yl/datai-com-text-pagination',
    componentName: '分页', // v7.0 index 3
    englishName: 'TextPagination',
    id: '1344243568107003906',
    imgUrl: 'assets/datai/icons/componentIcon/text/分页.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-progress-bar',
    componentName: '进度条', // v7.0 index 4
    englishName: 'ProgressBar',
    id: '1344243004342214658',
    imgUrl: 'assets/datai/icons/componentIcon/text/进度条.png',
    status: 1,
    version: '0.0.1',
  },

  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-dynamic-wordcloud',
    componentName: '动态词云', // v7.0 index 5
    englishName: 'DynamicWordcloud',
    id: '1344240725065146370',
    imgUrl: 'assets/datai/icons/componentIcon/text/动态词云.png',
    status: 1,
    version: '0.0.1',
    supportMobile: true,
  },
  {
    author: 'yangyongjian',
    componentCode: '@yl/datai-com-text-wordcloud',
    componentName: '词云', // v7.0 index 6 表格-其他
    englishName: 'TextWordcloud',
    id: '1344244674660868097',
    imgUrl: 'assets/datai/icons/componentIcon/text/词云.png',
    status: 1,
    version: '0.0.1',
  },

  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-text-tabs-group',
    componentName: 'tab切换组', // v7.0 index 7
    englishName: 'TextTabsGroup',
    id: '1344239840691953665',
    imgUrl: 'assets/datai/icons/componentIcon/text/tab.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'wangman',
    componentCode: '@yl/datai-com-text-tabs',
    componentName: 'Tab列表', // v7.0 index 8
    englishName: 'TextTabs',
    id: '1344243261507575810',
    imgUrl: 'assets/datai/icons/componentIcon/text/tabList.png',
    status: 1,
    version: '0.0.1',
    supportMobile: true,
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-text-tabs-select',
    componentName: '选择面板', // v7.0 index 9
    englishName: 'TextTabsSelect',
    id: '1344240783386943490',
    imgUrl: 'assets/datai/icons/componentIcon/text/tabSelect.png',
    status: 1,
    version: '0.0.1',
  },
  // {
  //   author: 'shaoyizhi',
  //   componentCode: '@yl/datai-com-text-search-group',
  //   componentName: '搜索组', // v7.0 index 10
  //   englishName: 'TextSearchGroup',
  //   id: '1344239794315534338',
  //   imgUrl: 'assets/datai/icons/componentIcon/text/textSearch.png',
  //   status: 1,
  //   version: '0.0.1',
  // },
  {
    author: 'yangguang',
    componentCode: '@yl/datai-com-text-score',
    componentName: '评分组件', // v7.0 index 11
    englishName: 'TextScore',
    id: '1344243497147768833',
    imgUrl: 'assets/datai/icons/componentIcon/text/星星.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'wangman',
    componentCode: '@yl/datai-com-text-digital-panel',
    componentName: '数字面板', // v7.0 index 12
    englishName: 'TextDigitalPanel',
    id: '1343912919661219841',
    imgUrl: 'assets/datai/icons/componentIcon/text/数字面板.png',
    status: 1,
    version: '0.0.1',
  },

  {
    author: 'wangman',
    componentCode: '@yl/datai-com-text-marquee',
    // componentName: '文字跑马灯',
    componentName: '横向跑马灯', // v7.0 index 13
    englishName: 'TextMarquee',
    id: '1344243944478679041',
    imgUrl: 'assets/datai/icons/componentIcon/text/文字跑马灯.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'wangman',
    componentCode: '@yl/datai-com-text-carouseltextlist',
    componentName: '文字轮播列表', // v7.0 index 14
    englishName: 'TextCarouseltextlist',
    id: '1344244038410117122',
    imgUrl: 'assets/datai/icons/componentIcon/text/文字轮播列表.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'wangman',
    componentCode: '@yl/datai-com-text-listturns',
    // componentName: '轮播列表柱状图', //v7.0 index 15
    componentName: '列表柱状图',
    englishName: 'TextListturns',
    id: '1344244114947776513',
    imgUrl: 'assets/datai/icons/componentIcon/text/轮播列表柱状图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'wangman',
    componentCode: '@yl/datai-com-text-overflowscroll',
    // componentName: '多行文本溢出滚动', // v7.0 index 16
    componentName: '纵向跑马灯',
    englishName: 'TextOverflowscroll',
    id: '1344243854326308865',
    imgUrl: 'assets/datai/icons/componentIcon/text/多行文本溢出滚动.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-time-picker',
    componentName: '时间选择器', // v7.0 index 17
    englishName: 'TimePicker',
    id: '1344240496328777729',
    imgUrl: 'assets/datai/icons/componentIcon/text/时间器.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-time-line',
    componentName: '时间轴', // v7.0 index 18
    englishName: 'TimeLine',
    id: '1344247071844016129',
    imgUrl: 'assets/datai/icons/componentIcon/text/时间轴.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'wangman',
    componentCode: '@yl/datai-com-text-time',
    componentName: '时间器', // v7.0 index 19
    englishName: 'TextTime',
    id: '1344247224948695042',
    imgUrl: 'assets/datai/icons/componentIcon/text/时间器.png',
    status: 1,
    version: '0.0.1',
    supportMobile: true,
  },

  {
    author: 'nerd',
    componentCode: '@yl/datai-chart-sankey',
    componentName: '桑基图', // v7.0 index 6 表格-其他
    englishName: 'Sankey',
    id: '7526454515009950819',
    imgUrl: 'assets/datai/icons/componentIcon/text/桑基图.svg',
    status: 1,
    version: '0.0.1',
  },
];
// 媒体组件 7
const mediaList = [
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-media-background-block-with-border',
    componentName: '背景板',
    englishName: 'MediaBackgroundBlockWithBorder',
    id: '1344238150945284097',
    imgUrl: 'assets/datai/icons/componentIcon/media/背景板.png',
    ion: '0.0.2',
    modifier: '20210508134141840584246283341824',
    status: 1,
    version: '0.0.1',
    supportMobile: true,
  },
  {
    author: 'xiachangwen',
    componentCode: '@yl/datai-com-media-decorate',
    componentName: '装饰',
    englishName: 'MediaDecorate',
    id: '1344242562933661697',
    imgUrl: 'assets/datai/icons/componentIcon/media/装饰.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'xuyonggang',
    componentCode: '@yl/datai-com-media-background-border',
    componentName: '边框',
    englishName: 'MediaBackgroundBorder',
    id: '1344239465528238082',
    imgUrl: 'assets/datai/icons/componentIcon/media/边框.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: '薛翠',
    componentCode: '@yl/datai-com-media-image-basic',
    componentName: '图片组件',
    englishName: 'MediaImageBasic',
    id: '1344238111392997378',
    imgUrl: 'assets/datai/icons/componentIcon/media/图片.png',
    status: 1,
    version: '8.7.0',
    supportMobile: true,
  },
  {
    author: '曾伟',
    componentCode: '@yl/datai-com-media-image-dynamic',
    componentName: 'URL图片',
    englishName: 'MediaImageDynamic',
    id: '1344238111392897379',
    imgUrl: 'assets/datai/icons/componentIcon/media/dynamicImage.png',
    status: 1,
    version: '8.7.0',
    supportMobile: true,
  },
  {
    author: '徐永刚',
    componentCode: '@yl/datai-com-media-background-block',
    componentName: '自定义背景块',
    englishName: 'MediaBackgroundBlock',
    id: '1344239565939875841',
    imgUrl: 'assets/datai/icons/componentIcon/media/自定义背景块.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: '邵明超',
    componentCode: '@yl/datai-com-media-mp4-player',
    componentName: 'MP4播放器',
    englishName: 'MediaMp4Player',
    id: '1344238230393790466',
    imgUrl: 'assets/datai/icons/componentIcon/media/mp4播放器.png',
    status: 1,
    version: '0.0.1',
  },
];

// TODO v8.11.0 替换缩略图
// 折线图 7
const lineChartList = [
  {
    author: '杨光',
    componentCode: '@yl/datai-com-chart-line-basic',
    componentName: '基础折线图',
    englishName: 'ChartLineBasic',
    id: '1344248937923420161',
    imgUrl: 'assets/datai/icons/componentIcon/chart/lineChart/折线图.png',
    status: 1,
    version: '0.0.1',
    supportMobile: true,
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-chart-area-broken',
    componentName: '区域折线图',
    englishName: 'ChartAreaBroken',
    id: '1344239321969795074',
    imgUrl: 'assets/datai/icons/componentIcon/chart/lineChart/区域折线图.png',
    status: 1,
    version: '0.0.1',
    supportMobile: true,
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-chart-line-sector',
    componentName: '分段折线图',
    englishName: 'ChartLineSector',
    id: '1344241276955860993',
    imgUrl: 'assets/datai/icons/componentIcon/chart/lineChart/分段折线图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: '李伟杰',
    componentCode: '@yl/datai-com-chart-mixed-line-bar',
    componentName: '折线柱状图',
    englishName: 'ChartMixedLineBar',
    id: '1344240122607902721',
    imgUrl: 'assets/datai/icons/componentIcon/chart/barChart/折线柱状图.png',
    status: 1,
    version: '0.0.1',
    supportMobile: true,
  },
  {
    author: '杨光',
    componentCode: '@yl/datai-com-chart-line-24h',
    componentName: '24小时折线图',
    englishName: 'ChartLine24h',
    id: '1344241864036786177',
    imgUrl: 'assets/datai/icons/componentIcon/chart/lineChart/24小时折线图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: '杨光',
    componentCode: '@yl/datai-com-chart-line-double-yaxis',
    componentName: '双轴折线图',
    englishName: 'ChartLineDoubleYaxis',
    id: '1344238555959861249',
    imgUrl: 'assets/datai/icons/componentIcon/chart/lineChart/双轴折线图.png',
    status: 1,
    version: '0.0.1',
    supportMobile: true,
  },
  {
    author: 'hanlong',
    componentCode: '@yl/datai-com-chart-line-more-yaxis',
    componentName: '多轴折线图',
    englishName: 'ChartLineMoreYaxis',
    id: '1344238555959861250',
    imgUrl: 'assets/datai/icons/componentIcon/chart/lineChart/多轴折线图.png',
    status: 1,
    version: '0.0.1',
  },
];
// 条形图 9
const barChartList = [
  {
    author: '杨光',
    componentCode: '@yl/datai-com-chart-bar-basic',
    componentName: '基础条形图',
    englishName: 'ChartBarBasic',
    id: '1344249114650419201',
    imgUrl: 'assets/datai/icons/componentIcon/chart/barChart/条形图.png',
    status: 1,
    version: '0.0.1',
    supportMobile: true,
  },
  {
    author: '杨光',
    componentCode: '@yl/datai-com-chart-bar-capsule',
    componentName: '胶囊条形图',
    englishName: 'ChartBarCapsule',
    id: '1344243194050584578',
    imgUrl: 'assets/datai/icons/componentIcon/chart/barChart/胶囊条形图.png',
    status: 1,
    version: '0.0.1',
    supportMobile: true,
  },
  {
    author: 'wangman',
    componentCode: '@yl/datai-com-chart-bar-stack-twoWay',
    componentName: '双向条形图',
    englishName: 'ChartBarStackTwoWay',
    id: '1344240187753832450',
    imgUrl: 'assets/datai/icons/componentIcon/chart/barChart/水平正负.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: '杨光',
    componentCode: '@yl/datai-com-chart-bar-group',
    componentName: '分组条形图',
    englishName: 'ChartBarGroup',
    id: '1362321331047890946',
    imgUrl: 'assets/datai/icons/componentIcon/chart/barChart/分组条形图.png',
    status: 1,
    version: '0.0.1',
    supportMobile: true,
  },
  {
    author: '杨光',
    componentCode: '@yl/datai-com-chart-bar-stack',
    componentName: '堆叠条形图',
    englishName: 'ChartBarStack',
    id: '1344246937856974849',
    imgUrl: 'assets/datai/icons/componentIcon/chart/barChart/堆叠条形图.png',
    status: 1,
    version: '0.0.1',
    supportMobile: true,
  },
  {
    author: '杨光',
    componentCode: '@yl/datai-com-chart-bar-double-y-capsule',
    componentName: '双Y轴条形图',
    englishName: 'ChartBarDoubleYCapsule',
    id: '1344237843704127490',
    imgUrl: 'assets/datai/icons/componentIcon/chart/barChart/双y轴条图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: '杨光',
    componentCode: '@yl/datai-com-chart-bar-area-map',
    componentName: '条形面积图',
    englishName: 'ChartBarAreaMap',
    id: '1344242712544485378',
    imgUrl: 'assets/datai/icons/componentIcon/chart/barChart/条形面积图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: '韩龙',
    componentCode: '@yl/datai-com-chart-column-dot',
    componentName: '圆圈条形图',
    englishName: 'ChartColumnDot',
    id: '1409425308363481090',
    imgUrl: 'assets/datai/icons/componentIcon/chart/barChart/圆圈条形图.png',
    status: 1,
    version: '0.0.1',
    supportMobile: true,
  },
];
// 柱状图 8
const columnChartList = [
  {
    author: '杨光',
    componentCode: '@yl/datai-com-chart-column-basic',
    componentName: '基础柱状图',
    englishName: 'ChartColumnBasic',
    id: '1344243664123011074',
    imgUrl: 'assets/datai/icons/componentIcon/chart/barChart/柱状图.png',
    status: 1,
    version: '0.0.1',
    supportMobile: true,
  },
  {
    author: '杨光',
    componentCode: '@yl/datai-com-chart-column-rainbow',
    componentName: '彩虹柱状图',
    englishName: 'ChartColumnRainbow',
    id: '1344240599349272577',
    imgUrl: 'assets/datai/icons/componentIcon/chart/barChart/彩虹柱状图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: '杨光',
    componentCode: '@yl/datai-com-chart-column-capsule',
    componentName: '胶囊柱状图',
    englishName: 'ChartColumnCapsule',
    id: '1344241015600390145',
    imgUrl: 'assets/datai/icons/componentIcon/chart/barChart/胶囊柱状图.png',
    status: 1,
    version: '0.0.1',
    supportMobile: true,
  },
  {
    author: '杨光',
    componentCode: '@yl/datai-com-chart-column-stack',
    componentName: '堆叠柱状图',
    englishName: 'ChartColumnStack',
    id: '1344241919078637570',
    imgUrl: 'assets/datai/icons/componentIcon/chart/barChart/堆叠柱形图.png',
    status: 1,
    version: '0.0.1',
    supportMobile: true,
  },
  {
    author: '杨光',
    componentCode: '@yl/datai-com-chart-column-vertical-group',
    componentName: '垂直分组柱状图',
    englishName: 'ChartColumnVerticalGroup',
    id: '1362343651888070658',
    imgUrl: 'assets/datai/icons/componentIcon/chart/barChart/垂直分组柱状图.png',
    status: 1,
    version: '0.0.1',
    supportMobile: true,
  },
  {
    author: '杨光',
    componentCode: '@yl/datai-com-chart-column-largearea-histogram',
    componentName: '大面积柱状图',
    englishName: 'ChartColumnLargeareaHistogram',
    id: '1367745970791546881',
    imgUrl: 'assets/datai/icons/componentIcon/chart/barChart/大面积柱状图.png',
    ion: '0.0.1',
    modifier: '20210508134141840584246283341824',
    status: 1,
    version: '0.0.1',
  },
  {
    author: '杨光',
    componentCode: '@yl/datai-com-chart-column-contrast-histogram',
    componentName: '单色对比柱状图',
    englishName: 'ChartColumnContrastHistogram',
    id: '1367746070330769410',
    imgUrl: 'assets/datai/icons/componentIcon/chart/barChart/单色对比柱状图.png',
    ion: '0.0.2',
    modifier: '20210508134141840584246283341824',
    status: 1,
    version: '0.0.1',
  },
  {
    author: '曾伟',
    componentCode: '@yl/datai-com-chart-column-cylinder',
    componentName: '圆柱柱状图',
    englishName: 'ChartColumnCylinder',
    id: '1398187308927152130',
    imgUrl: 'assets/datai/icons/componentIcon/chart/barChart/3D柱状图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: '吕博文',
    componentCode: '@yl/datai-com-chart-column-3d',
    componentName: '3D柱状图',
    englishName: 'ChartColumn3D',
    id: '1398187308927152131',
    imgUrl: 'assets/datai/icons/componentIcon/chart/barChart/真3D柱状图.svg',
    status: 1,
    version: '0.0.1',
  },
  {
    author: '吕博文',
    componentCode: '@yl/datai-com-chart-column-stickers',
    componentName: '贴图柱状图',
    englishName: 'ChartColumnStickers',
    id: '1398187308927152132',
    imgUrl: 'assets/datai/icons/componentIcon/chart/barChart/贴图柱状图.svg',
    status: 1,
    version: '0.0.1',
    supportMobile: true,
  },
];
// 饼图 9
const circleChartList = [
  {
    author: 'wangman',
    componentCode: '@yl/datai-com-chart-pie-chart',
    componentName: '饼形图',
    englishName: 'ChartPieChart',
    id: '1344248763444568066',
    imgUrl: 'assets/datai/icons/componentIcon/chart/cirleChart/环形图.png',
    status: 1,
    version: '0.0.1',
    supportMobile: true,
  },
  {
    author: 'wangman',
    componentCode: '@yl/datai-com-chart-circular',
    componentName: '环形图',
    englishName: 'ChartCircular',
    id: '1344244774669852673',
    imgUrl: 'assets/datai/icons/componentIcon/chart/cirleChart/环形图.png',
    status: 1,
    version: '0.0.1',
    supportMobile: true,
  },
  {
    author: '杨光',
    componentCode: '@yl/datai-com-chart-semicircle',
    componentName: '半圆形（试用）',
    englishName: 'ChartSemicircle',
    id: '1344247549172588545',
    imgUrl: 'assets/datai/icons/componentIcon/chart/cirleChart/环形图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'xiachangwen',
    componentCode: '@yl/datai-com-chart-rose-diagram',
    componentName: '玫瑰图',
    englishName: 'ChartRoseDiagram',
    id: '1344238641179729922',
    imgUrl: 'assets/datai/icons/componentIcon/chart/cirleChart/玫瑰图.png',
    status: 1,
    version: '0.0.1',
    supportMobile: true,
  },
  {
    author: 'liweijie',
    componentCode: '@yl/datai-com-chart-ring-bar',
    componentName: '环形柱图',
    englishName: 'ChartRingBar',
    id: '1344241616258277377',
    imgUrl: 'assets/datai/icons/componentIcon/chart/cirleChart/环形柱状图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'wangman',
    componentCode: '@yl/datai-com-chart-nestRing',
    componentName: '嵌套环形图',
    englishName: 'ChartNestRing',
    id: '1344244879821053954',
    imgUrl: 'assets/datai/icons/componentIcon/chart/cirleChart/嵌套环形图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'zhuyafei',
    componentCode: '@yl/datai-com-chart-ring-gauge',
    componentName: '环形百分比饼图',
    englishName: 'ChartRingGauge',
    id: '1344240069173221215',
    imgUrl: 'assets/datai/icons/componentIcon/chart/cirleChart/环形百分比饼图.png',
    status: 1,
    versionCode: '0.0.1',
  },
  antdCompList.find(({ englishName }) => englishName === 'PieChart3D'),
];
// 其他 7
const otherChartList = [
  {
    author: 'wangman',
    componentCode: '@yl/datai-com-chart-ranking-list',
    componentName: '排行榜',
    englishName: 'ChartRankingList',
    id: '1344239951941672961',
    imgUrl: 'assets/datai/icons/componentIcon/chart/barChart/排行榜.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'zhuyafei',
    componentCode: '@yl/datai-com-chart-heatmap',
    componentName: '热力图',
    englishName: 'ChartHeatmap',
    id: '1397880090986016770',
    imgUrl: 'assets/datai/icons/componentIcon/chart/otherChart/热力图.png',
    status: 1,
    version: '0.0.1',
  },
  // {
  //   author: 'wangman',
  //   componentCode: '@yl/datai-com-chart-pictograph',
  //   componentName: '象形柱图',
  //   englishName: 'ChartPictograph',
  //   id: '1344247374156865538',
  //   imgUrl: 'assets/datai/icons/componentIcon/chart/barChart/象形柱状图.png',
  //   status: 1,
  //   version: '0.0.1',
  // },
  {
    author: 'zhanzhixuan',
    componentCode: '@yl/datai-com-chart-polar',
    componentName: '极坐标堆叠柱图',
    englishName: 'ChartPolar',
    id: '1344248822303236097',
    imgUrl: 'assets/datai/icons/componentIcon/chart/barChart/极坐标堆叠.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'wangman',
    componentCode: '@yl/datai-com-chart-waterPol',
    componentName: '水波图',
    englishName: 'ChartWaterPol',
    id: '1344248730057908225',
    imgUrl: 'assets/datai/icons/componentIcon/chart/otherChart/水球图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'yangguang',
    componentCode: '@yl/datai-com-chart-scatter',
    componentName: '基本散点图',
    englishName: 'ChartScatter',
    id: '1344244204471001089',
    imgUrl: 'assets/datai/icons/componentIcon/chart/otherChart/散点层.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'yangyongjian',
    componentCode: '@yl/datai-com-chart-funnel',
    componentName: '漏斗图',
    englishName: 'ChartFunnel',
    id: '1344244562140274690',
    imgUrl: 'assets/datai/icons/componentIcon/chart/otherChart/漏斗图.png',
    status: 1,
    version: '0.0.1',
    supportMobile: true,
  },
  {
    author: '张熠',
    componentCode: '@yl/datai-com-chart-babel',
    componentName: '基本气泡图',
    englishName: 'ChartBabel',
    id: '1344244284888391682',
    imgUrl: 'assets/datai/icons/componentIcon/chart/otherChart/气泡图.png',
    status: 1,
    version: '0.0.1',
  },
  // v7.0
  {
    author: 'liweijie',
    componentCode: '@yl/datai-com-chart-gauge',
    componentName: '仪表盘',
    englishName: 'ChartGauge',
    id: '1344248906008961026',
    imgUrl: 'assets/datai/icons/componentIcon/chart/otherChart/仪表盘.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'liweijie',
    componentCode: '@yl/datai-com-chart-d-gauge',
    componentName: '双仪表盘',
    englishName: 'ChartDGauge',
    id: '1344240069172469761',
    imgUrl: 'assets/datai/icons/componentIcon/chart/otherChart/双仪表盘.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: '杨光',
    componentCode: '@yl/datai-com-chart-radar',
    componentName: '雷达图',
    englishName: 'ChartRadar',
    id: '1344249299266904065',
    imgUrl: 'assets/datai/icons/componentIcon/chart/otherChart/雷达图.png',
    status: 1,
    version: '0.0.1',
    supportMobile: true,
  },
  // v8.14 添加矩形树图
  {
    author: '赵晶晶',
    componentCode: '@yl/datai-chart-treemap',
    componentName: '矩形树图',
    englishName: 'ChartTreemap',
    id: '1344241718072388204',
    imgUrl: 'assets/datai/icons/componentIcon/chart/otherChart/矩形树图.png',
    status: 1,
    version: '0.0.1',
  },
];

// 地图容器 3
const mapContainerList = [
  {
    author: '杨云帅',
    componentCode: '@yl/datai-com-map-foundationPlan',
    // componentName: '基础平面图', // v7.0 index 0
    componentName: '二维地图',
    englishName: 'MapFoundationPlan',
    id: '1344249189208367105',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/2d基础平面图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'wangman',
    componentCode: '@yl/datai-com-map-gl-FoundationPlan',
    // componentName: 'datai.gl地图', // v7.0 index 1
    componentName: 'GL地图',
    englishName: 'MapGlFoundationPlan',
    id: '1344240658585427970',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/gl地图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'wangman',
    componentCode: '@yl/datai-com-map-3D-FoundationPlan',
    // componentName: 'datai.3D地图', // v7.0 index 2
    componentName: '三维地图',
    englishName: 'Map3DFoundationPlan',
    id: '1344240399247417345',
    imgUrl: 'assets/datai/icons/componentIcon/3dMap/3dMap.png',
    status: 1,
    version: '0.0.1',
  },
];

// 2d地图子组件 17个
export const map2dList = [
  {
    author: '赵天喜',
    componentCode: '@yl/datai-com-map-gaud-online',
    componentName: '在线底图',
    englishName: 'MapGaudOnline',
    id: '1344239508993810434',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/高德在线地图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'Bernard',
    componentCode: '@yl/datai-com-map-base-point-layer',
    componentName: '基础点图层',
    englishName: 'BasePointLayer',
    id: '1344243738961977346',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/base_point_layer_comp_icon.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'hanlong',
    componentCode: '@yl/datai-com-map-2d-gif-layer',
    componentName: '动态点图层',
    englishName: 'BaseGifLayer2D',
    id: '1344238325499634577',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/point-gif.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'Bernard',
    componentCode: '@yl/datai-com-map-base-polyline-layer',
    componentName: '基础线图层',
    englishName: 'BasePolylineLayer',
    id: '1344243738961977347',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/base_polyline_layer_comp_icon.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'Bernard',
    componentCode: '@yl/datai-com-map-base-polygon-layer',
    componentName: '基础面图层',
    englishName: 'BasePolygonLayer',
    id: '1344243738961977348',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/base_polygon_layer_comp_icon.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'Bernard',
    componentCode: '@yl/datai-com-map-mask-layer',
    componentName: '蒙层',
    englishName: 'MaskLayer',
    id: '1344243738961977349',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/mask_layer_comp_icon.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: '赵天喜',
    componentCode: '@yl/datai-com-map-hotmap',
    componentName: '热力图',
    englishName: 'MapHotmap',
    id: '1344247976567971841',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/热力图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'zhuyafei',
    componentCode: '@yl/datai-com-map-interpolation',
    componentName: '插值图',
    englishName: 'MapInterpolation',
    id: '1344247977567971832',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/插值图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'lvbowen',
    componentCode: '@yl/datai-com-map-contour',
    componentName: '等值线面图',
    englishName: 'MapContour',
    id: '1344247977567971123',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/等值线面图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: '赵天喜',
    componentCode: '@yl/datai-com-map-breath-bubble-layer',
    componentName: '呼吸气泡层',
    englishName: 'MapBreathBubbleLayer',
    id: '1344238488842608642',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/呼吸气泡层.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'hanlong',
    componentCode: '@yl/datai-com-map-2d-point-polymerization',
    componentName: '点聚合',
    englishName: 'Map2DPointPolymerization',
    id: '1344240024192757512',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/点聚合.png',
    status: 1,
    version: '0.0.1',
  },

  // {
  //   author: '赵天喜',
  //   componentCode: '@yl/datai-com-map-point-polymerization',
  //   componentName: '点聚合',
  //   englishName: 'MapPointPolymerization',
  //   id: '1344240024192753665',
  //   imgUrl: 'assets/datai/icons/componentIcon/2dMap/点聚合.png',
  //   status: 1,
  //   version: '0.0.1'
  // },
  {
    author: '赵天喜',
    componentCode: '@yl/datai-com-map-fly-list',
    componentName: '飞线层',
    englishName: 'MapFlyList',
    id: '1344240341290524674',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/飞线层.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: '杨光',
    componentCode: '@yl/datai-com-map-covering-layer',
    componentName: '遮盖图层',
    englishName: 'MapCoveringLayer',
    id: '1344241156549976066',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/遮罩层.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: '杨云帅',
    componentCode: '@yl/datai-com-map-leader-line',
    componentName: '指引线',
    englishName: 'MapLeaderLine',
    id: '1344242292988256257',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/指引线.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: '杨云帅',
    componentCode: '@yl/datai-com-map-sandian',
    componentName: '散点层',
    englishName: 'MapSandian',
    id: '1344248395012710402',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/散点层.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: '赵天喜',
    componentCode: '@yl/datai-com-map-regional-heating',
    componentName: '区域热力层',
    englishName: 'MapRegionalHeating',
    id: '1344241343611740161',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/区域热力层.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-path-line',
    componentName: '轨迹飞线',
    englishName: 'MapPathLine',
    id: '1344242867977003009',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/轨迹飞线.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: '杨云帅',
    componentCode: '@yl/datai-com-map-background-layer',
    componentName: '背景层',
    englishName: 'MapBackgroundLayer',
    id: '1344243738961977345',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/背景层.png',
    status: 1,
    version: '0.0.1',
  },
];
// gl地图子组件 21个
export const mapGlList = [
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-gl-basic-layer-new',
    componentName: '基础底图',
    englishName: 'MapGlBasicLayerNew',
    id: '1344241422041030657',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/gl基础底图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-gl-basic-point-layer',
    componentName: '基础点图层',
    englishName: 'MapGlBasePointLayer',
    id: '1344241692696280455',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/base_point_layer_comp_icon.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-gl-basic-polyline-layer',
    componentName: '基础线图层',
    englishName: 'MapGlBasePolylineLayer',
    id: '1344241692696649571',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/base_polyline_layer_comp_icon.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-gl-base-polygon-layer',
    componentName: '基础面图层',
    englishName: 'MapGLBasePolygonLayer',
    id: '1344241692696649571',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/base_polygon_layer_comp_icon.png',
    status: 1,
    version: '0.0.1',
  },
  // v8.3
  {
    author: 'zhaojingjing',
    componentCode: '@yl/datai-com-map-gl-plate-layer',
    componentName: 'gl板块图',
    englishName: 'MapGLPlateLayer',
    id: '1344238453287493571',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/板块图.png',
    status: 1,
    version: '0.0.1',
  },
  // v8.10.0 gl热力图
  {
    author: 'zhaojingjing',
    componentCode: '@yl/datai-com-map-gl-heat-map-new',
    componentName: '热力图',
    englishName: 'MapGlHeatMapNew',
    id: '1344243411063873538',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/线热力图.png',
    status: 1,
    version: '0.0.1',
  },
  // v8.10.0 白模图层
  {
    author: 'zhaojingjing',
    componentCode: '@yl/datai-com-map-gl-buiding-layer-new',
    componentName: '白模图层',
    englishName: 'MapGlBuildingLayerNew',
    id: '1344240259048611842',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/建筑贴图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'hanlong',
    componentCode: '@yl/datai-com-map-gl-geo-fencing-new',
    componentName: '地理围栏',
    englishName: 'MapGlGeoFencingNew',
    id: '1344238325499633665',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/地理围栏.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-gl-scene-controller',
    componentName: '场景管理器',
    englishName: 'MapGlSceneController',
    id: '1344238453287493634',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/轨迹飞线.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-gl-circle',
    componentName: '动画点标记',
    englishName: 'MapGlCircle',
    id: '1344243329295917057',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/动画点标记.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-gl-cylinder',
    componentName: 'gl圆柱',
    englishName: 'MapGlCylinder',
    id: '1344240910440800258',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/线热力图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-gl-dynamics-point',
    componentName: '发光图标',
    englishName: 'MapGlDynamicsPoint',
    id: '1344238915457851393',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/气泡飞线.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-gl-fly-line',
    componentName: 'gl轨迹飞线',
    englishName: 'MapGlFlyLine',
    id: '1344241215995846657',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/轨迹飞线.png',
    status: 1,
    version: '0.0.1',
  },

  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-gl-info-window',
    componentName: '信息窗体',
    englishName: 'MapGlInfoWindow',
    id: '1344238371225935874',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/信息窗体.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-gl-line-heat',
    componentName: '线热力图',
    englishName: 'MapGlLineHeat',
    id: '1344241805073260545',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/线热力图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-gl-path-planning',
    componentName: 'gl路线规划',
    englishName: 'MapGlPathPlanning',
    id: '1344238296252751874',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/轨迹飞线.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-gl-region-line',
    componentName: '区域线',
    englishName: 'MapGlRegionLine',
    id: '1344242210050088962',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/区域线.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-gl-region-mask',
    componentName: '区域遮罩层',
    englishName: 'MapGlRegionMask',
    id: '1344239892294475778',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/区域遮罩层.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-gl-region-plate',
    componentName: '区域板块',
    englishName: 'MapGlRegionPlate',
    id: '1344239068658999298',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/轨迹飞线.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-gl-region-heat',
    componentName: 'gl区域热力层',
    englishName: 'MapGlRegionHeat',
    id: '1344240546329075714',
    imgUrl: 'assets//datai/icons/componentIcon/glMap/gl热力层.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-gl-rainbow-line',
    componentName: '彩虹飞线',
    englishName: 'MapGlRainbowLine',
    id: '1344240838990831618',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/气泡飞线.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-gl-BubbleFlyLine',
    componentName: '气泡飞线',
    englishName: 'MapGlBubbleFlyLine',
    id: '1344242402266652673',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/气泡飞线.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-gl-cube-maps',
    componentName: '立体贴图',
    englishName: 'MapGlCubeMaps',
    id: '1344242934624493570',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/信息窗体.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-gl-static-sign',
    componentName: '静态图标',
    englishName: 'MapGlStaticSign',
    id: '1344238406843965441',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/静态图标.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-gl-mask-layer',
    componentName: 'gl图层蒙版',
    englishName: 'MapGlMaskLayer',
    id: '1344239750854156289',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/轨迹飞线.png',
    status: 1,
    version: '0.0.1',
  },
];
// 3d地图子组件 14个
export const map3dList = [
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-3D-basic-layer',
    componentName: '3d基础底图',
    englishName: 'Map3DBasicLayer',
    id: '1344240958528495617',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/gl基础底图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'Bernard',
    componentCode: '@yl/datai-com-map-3D-base-point-layer',
    componentName: '基础点图层',
    englishName: 'BasePointLayer3D',
    id: '1351774326670966786',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/base_point_layer_comp_icon.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'hanlong',
    componentCode: '@yl/datai-com-map-3d-gif-layer',
    componentName: '动态点图层',
    englishName: 'BaseGifLayer3D',
    id: '1344238325499634577',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/point-gif.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'Bernard',
    componentCode: '@yl/datai-com-map-3D-base-polyline-layer',
    componentName: '基础线图层',
    englishName: 'BasePolylineLayer3D',
    id: '1351774326670966787',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/base_polyline_layer_comp_icon.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'Bernard',
    componentCode: '@yl/datai-com-map-3D-base-polygon-layer',
    componentName: '基础面图层',
    englishName: 'BasePolygonLayer3D',
    id: '1351774326670966788',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/base_polygon_layer_comp_icon.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'lvbowen',
    componentCode: '@yl/datai-com-map-3D-cim-visual-template',
    componentName: '孪生底板',
    englishName: 'Map3DCimVisualTemplate',
    id: '1344238699186954242',
    imgUrl: 'assets/datai/icons/componentIcon/3dMap/visualTemplate.png',
    status: 1,
    version: '0.0.1',
  },

  {
    author: 'zhaojigjing',
    componentCode: '@yl/datai-com-map-3D-buiding-layer',
    componentName: '3d-白模图层',
    englishName: 'Map3DBuildingLayer',
    id: '1344238699186956785',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/建筑贴图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'hanlong',
    componentCode: '@yl/datai-com-map-3D-geo-fencing',
    componentName: '3d-地理围栏',
    englishName: 'Map3DGeoFencing',
    id: '1344238325499633689',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/地理围栏.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-3D-tileset-layer',
    componentName: '3d-倾斜摄影',
    englishName: 'Map3DTilesetLayer',
    id: '1344238699186954242',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/gl基础底图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-3D-heatMap-layer',
    componentName: '3d-热力图',
    englishName: 'Map3DHeatMapLayer',
    id: '1344238729616629762',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/gl基础底图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'zhuyafei',
    componentCode: '@yl/datai-com-map-3D-interpolation',
    componentName: '3d-插值图',
    englishName: 'Map3DInterpolationLayer',
    id: '1344238729166691323',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/插值图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'lvbowen',
    componentCode: '@yl/datai-com-map-3D-contour',
    componentName: '3d-等值线面图',
    englishName: 'Map3DContour',
    id: '1344238729166691112',
    imgUrl: 'assets/datai/icons/componentIcon/2dMap/等值线面图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'hanlong',
    componentCode: '@yl/datai-com-map-3d-point-polymerization',
    componentName: '3d-点聚合',
    englishName: 'Map3DPointPolymerization',
    id: '1344231659685403290',
    imgUrl: 'assets/datai/icons/componentIcon/3dMap/点聚合.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'zhuyafei',
    componentCode: '@yl/datai-com-map-3D-threed-layer',
    componentName: '3d-三维瓦片',
    englishName: 'Map3DThreedLayer',
    id: '1344238699186953333',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/gl基础底图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-3D-circle-layer',
    componentName: '3d-区域圆(柱)',
    englishName: 'Map3DCircleLayer',
    id: '1344239378714533889',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/gl基础底图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-3D-line-layer',
    componentName: '3d-区域线',
    englishName: 'Map3DLineLayer',
    id: '1344241690799448065',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/gl基础底图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-3D-marker-layer',
    componentName: '3d-点标记',
    englishName: 'Map3DMarkerLayer',
    id: '1344238762474807298',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/gl基础底图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-3D-polygon-layer',
    componentName: '3d-区域面',
    englishName: 'Map3DPolygonLayer',
    id: '1344238798499684353',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/gl基础底图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-3D-text-layer',
    componentName: '3d-文本标记',
    englishName: 'Map3DTextLayer',
    id: '1344242068853039106',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/gl基础底图.png',
    status: 1,
    version: '0.0.1',
  },
  {
    author: 'shaoyizhi',
    componentCode: '@yl/datai-com-map-3D-gltf-model-layer',
    componentName: '3d-三维模型',
    englishName: 'Map3DGltfModelLayer',
    id: '1351774326670966785',
    imgUrl: 'assets/datai/icons/componentIcon/glMap/gl基础底图.png',
    status: 1,
    version: '0.0.1',
  },
];

export const mapTypeList = [
  {
    layersName: 'map2dLayers',
    mapList: map2dList, // 2d地图
  },
  {
    layersName: 'mapGlLayers',
    mapList: mapGlList, // GL地图
  },
  {
    layersName: 'map3dLayers',
    mapList: map3dList, // 3d地图
  },
];

// 报表组件
export const compChartList = {
  lineChartList,
  barChartList,
  columnChartList,
  circleChartList,
  otherChartList,
};

// 122个组件
export const compVersionList = [
  ...groupList,
  ...basicTextList,
  ...mediaList,
  ...lineChartList,
  ...barChartList,
  ...columnChartList,
  ...circleChartList,
  ...otherChartList,
  ...mapContainerList,
  ...map2dList,
  ...mapGlList,
  ...map3dList,
];

// v7.0修改组件分类
export const categoryListTree = [
  {
    categoryCode: 'text',
    categoryName: '显示组件',
    id: 1,
    parentId: 0,
    imageUrl: 'assets/datai/icons/显示@2x.png',
    children: [
      {
        categoryCode: 'textBasic',
        categoryName: '文本',
        id: 11,
        parentId: 1,
        versions: [
          antdCompList[0], // 文本组件（antd）
          antdCompList[2], // 指标文本（antd）
          basicTextList[12], // 文字跑马灯（改名横向跑马灯）
          basicTextList[15], // 多行文本溢出滚动（改名纵向跑马灯）
          basicTextList[18], // 时间器
        ],
      },
      {
        categoryCode: 'effects',
        categoryName: '特效',
        id: 12,
        parentId: 1,
        versions: [
          basicTextList[2], // 翻牌器
          basicTextList[17], // 时间轴
          basicTextList[4], // 进度条
          basicTextList[10], // 评分组件
          basicTextList[3], // 分页
        ],
      },
    ],
  },
  {
    categoryCode: 'form',
    categoryName: '表格',
    id: 2,
    parentId: 0,
    imageUrl: 'assets/datai/icons/表格@2x.png', // v7.0修改
    children: [
      {
        categoryCode: 'form',
        categoryName: '表格',
        id: 21,
        parentId: 2,
        show: true,
        versions: [
          antdCompList[4], // 表格组件
          antdCompList[5], // 描述列表
          antdCompList[14], // 列表（改名多行列表）
          antdCompList[15], // 树形列表
          basicTextList[14], // 轮播列表柱状图（改名列表柱状图）
          basicTextList[13], // 文字轮播列表
        ],
      },
    ],
  },
  {
    categoryCode: 'chart',
    categoryName: '报表',
    id: 3,
    parentId: 0,
    imageUrl: 'assets/datai/icons/报表@2x.png',
    children: [
      {
        categoryCode: 'chartLine',
        categoryName: '折线图',
        id: 31,
        parentId: 3,
        versions: [...lineChartList],
      },
      {
        categoryCode: 'chartStripSta1',
        categoryName: '条形图',
        id: 32,
        parentId: 3,
        versions: [...barChartList],
      },
      {
        categoryCode: 'chartBar',
        categoryName: '柱状图',
        id: 33,
        parentId: 3,
        versions: [...columnChartList],
      },
      {
        categoryCode: 'chartPie',
        categoryName: '饼图',
        id: 34,
        parentId: 3,
        versions: [...circleChartList],
      },
      {
        categoryCode: 'chartOthers',
        categoryName: '其他',
        id: 35,
        parentId: 3,
        versions: [
          ...otherChartList,
          basicTextList[5],
          basicTextList[6],
          basicTextList.find(({ componentCode }) => componentCode === '@yl/datai-chart-sankey'),
        ],
      },
    ],
  },
  {
    categoryCode: 'media',
    categoryName: '多媒体',
    id: 4,
    parentId: 0,
    imageUrl: 'assets/datai/icons/媒体@2x.png',
    children: [
      {
        categoryCode: 'mediaImage',
        categoryName: '图片',
        id: 41,
        parentId: 4,
        show: true,
        versions: [
          ...mediaList.slice(0, 6),
          {
            author: 'Bernard',
            componentName: '布局模板',
            englishName: 'CardTemplate',
            parentType: 'antd',
            imgUrl: 'assets/datai/icons/componentIcon/media/CardTemplateIcon.png',
          },
          {
            author: 'hanlong',
            componentName: '全景图',
            englishName: 'PanoramaMap',
            parentType: 'antd',
            imgUrl: 'assets/datai/icons/componentIcon/media/PanoramaMapIcon.png',
          },
        ],
      },
      {
        categoryCode: 'mediaPlayer',
        categoryName: '播放器',
        id: 42,
        parentId: 4,
        versions: [
          ...mediaList.slice(6),
          {
            author: 'zengwei',
            componentName: '通用播放器',
            englishName: 'UniversalPlayer',
            parentType: 'antd',
            imgUrl: 'assets/datai/icons/componentIcon/media/rtmp播放器.png',
            status: 1,
            supportMobile: true,
          },
          {
            author: 'hanlong',
            componentName: '视频流播放器',
            englishName: 'JessiucaPlayer',
            parentType: 'antd',
            imgUrl: 'assets/datai/icons/componentIcon/media/jessibucaPlayer.png',
            status: 1,
            supportMobile: true,
          },
        ],
      },
      {
        categoryCode: 'mediaSwiper',
        categoryName: '轮播组件',
        id: 43,
        parentId: 4,
        show: true,
        versions: [
          {
            author: '陈龙',
            componentName: '多媒体轮播',
            englishName: 'VisualSwiper',
            parentType: 'antd',
            imgUrl: 'assets/datai/icons/componentIcon/media/visualSwiper.png',
            supportMobile: true,
          },
        ],
      },
    ],
  },
  {
    categoryCode: 'controls',
    categoryName: '控件',
    id: 5,
    parentId: 0,
    imageUrl: 'assets/datai/icons/控件@2x.png',
    children: [
      {
        categoryCode: 'button',
        categoryName: '按钮',
        id: 51,
        parentId: 5,
        versions: [
          antdCompList[1], // 按钮组件
          antdCompList[3], // 多按钮
        ],
      },
      {
        categoryCode: 'inputControls',
        categoryName: '输入控件',
        id: 52,
        parentId: 5,
        versions: [
          // basicTextList[10], // 搜索组 v8.1.0 下掉
          antdCompList[19], // 输入框
          antdCompList[6], // 文本域
        ],
      },
      {
        categoryCode: 'selectControls',
        categoryName: '选择控件',
        id: 53,
        parentId: 5,
        versions: [
          // basicTextList[7], // tab切换组 v8.5.1删除组件
          basicTextList[8], // tab列表
          basicTextList[9], // 选择面板
          // basicTextList[17], // 时间选择器 v7.6.0删除组件
          basicTextList[17], // 时间轴（复用）
          antdCompList[7], // 复选框
          antdCompList[10], // 时间选择器（antd）
          antdCompList[11], // 下拉选择器
          antdCompList[12], // 树形选择器
          antdCompList[13], // 日历卡片
          antdCompList[15], // 树形列表（复用）
          antdCompList[16], // 单选框
          antdCompList[17], // 颜色选择器
          layerPageCompList[0], // 页面选择
        ],
      },
      {
        categoryCode: 'containerControls',
        categoryName: '容器控件',
        id: 54,
        parentId: 5,
        versions: [
          antdCompList[9], // 动态面板
          antdCompList[18], // iframe
          antdCompList[20], // 自定义列表
          antdCompList[23], // 自定义单元格
          antdCompList[24], // 折叠面板
        ],
      },
    ],
  },
  {
    categoryCode: 'map', // 用于过滤地图组价
    categoryName: '地图',
    id: 6,
    parentId: 0,
    imageUrl: 'assets/datai/icons/地图@2x.png',
    children: [
      {
        categoryCode: 'mapControls',
        categoryName: '地图组件',
        id: 61,
        parentId: 6,
        versions: [
          mapContainerList[0], // 基础平面图（改名二维地图）
          mapContainerList[1], // datai.gl地图（改名GL地图）
          mapContainerList[2], // datai.3D地图（改名三维地图）
          {
            ...mapContainerList[2],
            componentName: '三维地图(超图)',
            imgUrl: 'assets/datai/icons/componentIcon/3dMap/superMap.png',
          },
          // {
          //   author: 'zengwei',
          //   componentName: '云端场景',
          //   englishName: 'UnrealEngine',
          //   parentType: 'UnrealEngine',
          //   imgUrl: 'assets/datai/icons/componentIcon/mapInteraction/unrealEngine.png',
          // }, // 云端场景
          {
            author: 'chenlong',
            componentName: '外部场景',
            englishName: 'SceneFrame',
            parentType: 'SceneFrame',
            imgUrl: 'assets/datai/icons/componentIcon/media/sceneFrame.png',
          }, // 基础场景（改名外部场景）
        ],
      },
      {
        categoryCode: 'mapInteraction',
        categoryName: '地图交互',
        id: 62,
        parentId: 6,
        show: true,
        versions: [
          mapInteractionCompList[0], // 网格选择
          mapInteractionCompList[1], // 图层树
          mapInteractionCompList[2], // 图层图例
          mapInteractionCompList[3], // 比例尺
          mapInteractionCompList[4], // 地图标牌
          OneMapCompList[0], // 图层搜索
        ],
      },
    ],
  },
  {
    categoryCode: 'custom', // 用于区分获取自定义组件列表
    categoryName: '自定义组件',
    id: 8,
    parentId: 0,
    imageUrl: 'assets/datai/icons/自定义.png',
    children: [
      {
        categoryCode: 'customCom',
        categoryName: '自定义组件',
        id: 81,
        parentId: 5,
        versions: [],
      },
    ],
  },
];
