import { TemplateType } from '@/theme/TemplateManager/type';

export default {
  name: '基础饼状图',
  thumbnail: 'assets/templates/chartPieChart_default.png',
  from: 'datai',
  attr: {
    position: {
      sizeRateType: false,
      innerRadius: 0,
      outerRadius: 80,
      positionRateType: true,
      y: 50,
      x: 32,
    },
    ariaStyle: {
      barFillType: 'SolidColor',
    },
    shadow: {
      isShadow: false,
      isBorder: false,
    },
    label: {
      labelPosition: 'inner',
      labelStyleFixed: false,
      draftLineShow: false,
      lableVisible: true,
      labelNumberVisible: true,
      numberColor: '#FFFFFF',
      numberFontSize: 14,
      numberFontWeight: 'normal',
    },
    legend: {
      show: true,
      orient: false,
      align: 'left',
      paddingLeft: 0,
      paddingRight: 0,
      legendPositionRate: true,
      isTopComputed: true,
      fontFamily: 'Microsoft Yahei',
      icon: 'rect',
      itemGap: 15,
      itemWidth: 6,
      itemHeight: 4,
      top: 31,
      left: 62,
      right: 17,
      fontSize: 14,
      textColor: '#95A0B8',
      namePaddingLeft: 0,
      namePaddingRight: 0,
      namePaddingTop: 0,
      namePaddingBottom: 0,
      percentShow: true,
      percentBreakValue: false,
      percentFontSize: 14,
      percentPaddingLeft: 5,
      percentPaddingRight: 0,
      percentPaddingTop: 0,
      percentPaddingBottom: 0,
      percentTextColor: '#fff',
    },
  },
} as const satisfies TemplateType;
