import { TemplateType } from '@/theme/TemplateManager/type';

export default {
  name: '外部标签饼状图',
  thumbnail: 'assets/templates/chartPieChart_temp1.png',
  from: 'datai',
  attr: {
    position: {
      sizeRateType: false,
      innerRadius: 0,
      outerRadius: 90,
      positionRateType: true,
      x: 50,
      y: 50,
    },
    label: {
      labelPosition: 'outside',
      labelStyleFixed: true,
      draftLineShow: true,
      lableVisible: true,
      labelFontSize: 14,
      labelFontWeight: 'normal',
      labelColor: '#95A0B8',
      labelLineColor: 'rgba(255,255,255,0.3)',
      lineHeight: 28,
      labelNumberVisible: true,
      numberColor: '#FFFFFF',
      numberFontSize: 14,
      numberFontWeight: 'normal',
    },
    legend: {
      show: false,
      orient: true,
      icon: 'rect',
      itemGap: 10,
      itemWidth: 6,
      itemHeight: 4,
      top: 5,
      left: 15,
      right: 0,
      textColor: '#fff',
      percentShow: false,
      fontSize: 14,
      percentFontSize: 14,
      percentPaddingLeft: 0,
      percentPaddingBottom: 25,
    },
  },
} as const satisfies TemplateType;
