import { TemplateType } from '@/theme/TemplateManager/type';

export default {
  name: '基础3D饼图',
  thumbnail: 'assets/templates/PieChart3D.png',
  from: 'antd',
  attr: {
    props: {
      viewPort: { xRotation: -60, yRotation: 0 },
      pieStyle: { radiusInner: 0, radius: 50 },
      light: {
        mainLightColor: '#ffffff',
        mainLightRadiation: 19,
        mainLightRotation: { xRotation: 37, yRotation: 78 },
        ambientLightColor: '#ffffff',
        ambientLightRadiation: 9,
        isUseShadowMapping: false,
      },
      legend: {
        isShow: true,
        sort: 'default',
        layout: 'vertical',
        columnsNumber: 1,
        rowSpacing: 15,
        columnSpacing: 10,
        offset: [290, 77],
        alignWay: 'following',
        iconShape: 'rect',
        iconWidth: 12,
        iconHeight: 5,
        category: {
          isShow: true,
          colorExtends: false,
          offset: [0, 0],
          font: { fontFamily: 'Microsoft Yahei', fontSize: 14, fontWeight: 'normal', color: 'rgba(196, 196, 196, 1)' },
          overflow: 'ellipsis',
          width: 20,
          maxWidth: 50,
          lineHeight: 1,
        },
        nature: {
          suffix: {
            isShow: false,
            content: '',
            paddingLeft: 10,
            font: { fontFamily: 'Microsoft Yahei', fontSize: 14, fontWeight: 'normal', color: '#ffffff' },
          },
          isShow: false,
          colorExtends: true,
          offset: [0, 0],
          font: { fontFamily: 'Microsoft Yahei', fontSize: 14, fontWeight: 'normal', color: '#ffffff' },
          overflow: 'ellipsis',
          width: 20,
          maxWidth: 50,
          lineHeight: 1,
        },
        proportion: {
          isShow: true,
          colorExtends: false,
          offset: [0, 0],
          font: { fontFamily: 'Microsoft Yahei', fontSize: 14, fontWeight: 'normal', color: '#ffffff' },
          overflow: 'ellipsis',
          width: 20,
          maxWidth: 50,
          lineHeight: 1,
          decimalPlaces: 0,
        },
      },
      centerLabel: {
        isShow: false,
        category: {
          isShow: true,
          colorExtends: false,
          offset: [0, 0],
          font: { fontFamily: 'Microsoft Yahei', fontSize: 14, fontWeight: 'normal', color: '#ffffff' },
          overflow: 'wrap',
          width: 20,
          maxWidth: 127,
          lineHeight: 2,
        },
        nature: {
          suffix: {
            isShow: false,
            content: '',
            paddingLeft: 10,
            font: { fontFamily: 'Microsoft Yahei', fontSize: 14, fontWeight: 'normal', color: '#ffffff' },
          },
          isShow: false,
          colorExtends: false,
          offset: [0, 0],
          font: { fontFamily: 'Microsoft Yahei', fontSize: 14, fontWeight: 'normal', color: '#ffffff' },
          overflow: 'ellipsis',
          width: 20,
          maxWidth: 120,
          lineHeight: 1,
        },
        proportion: {
          isShow: true,
          colorExtends: false,
          offset: [0, -25],
          font: { fontFamily: 'Microsoft Yahei', fontSize: 30, fontWeight: 'normal', color: '#ffffff' },
          overflow: 'ellipsis',
          width: 20,
          maxWidth: 120,
          lineHeight: 1,
          decimalPlaces: 0,
        },
      },
      animation: { carousel: { isPauseWhenHover: true, isShowTooltip: true, isShowCenterLabel: false } },
    },
  },
} as const satisfies TemplateType;
